### ISSUE TITLE
Page 383, # 5. => Runtime Identifiers

### ISSUE THREAD

**Issue by centpede** [markjprice/cs12dotnet8#10]
Dear Mark,

the following runntime identifiers are not working (compiler error):

```
win10-x64 // should be win-x64?
win10-arm64 // should be win-arm64?
osx.11.0-arm64 // should be osx-arm64?
```
[Source](https://learn.microsoft.com/de-de/dotnet/core/rid-catalog)

Thanks,
Robin

**Comment by markjprice** [comment]
Yes, this is already in the errata:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-386---publishing-a-self-contained-app
