### ISSUE TITLE
Appendix A link under Bonus Content is broken

### ISSUE THREAD

**Issue by mkolassa** [markjprice/cs12dotnet8#2]
The [Appendix A](https://static.packt-cdn.com/downloads/9781837635870_Appendix.pdf) link returns an 'Access Denied' message.

**Comment by mkolassa** [comment]
For others while this link is broken, I believe this is the same document.

[docs/B19586_Appendix.pdf](https://github.com/markjprice/cs12dotnet8/blob/main/docs/B19586_Appendix.pdf)

**Comment by markjprice** [comment]
Thanks! I've fixed the link to point to my local copy of the PDF. I've also asked Packt to check their server and set correct permissions. I think they protect them until publish date but sometimes forget to enable them!
