### ISSUE TITLE
Answers to Knowledge Questions

### ISSUE THREAD

**Issue by johnml49** [markjprice/cs12dotnet8#20]
Where are the answers to the knowledge questions in Chapter 2 and all?  I've looked thoroughly through the readme sections and others but cannot find it.

**Comment by markjprice** [comment]
In the GitHub README:
https://github.com/markjprice/cs12dotnet8?tab=readme-ov-file#bonus-content

![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/2cf6f6ce-21d8-4a10-9cc8-5595c0627a01)

Also in the Preface:

![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/2bdda518-4349-4162-ae93-b08d9f4cc6b7)
