### ISSUE TITLE
Problem in source code, but book listing is correct

### ISSUE THREAD

**Issue by calupca** [markjprice/cs12dotnet8#21]
In 
```
code/Chapter02/Formatting/Program.cs
```

Line 24,

```
  "{0} {1} lived in {2} and worked in the {4} team at {5}."
```

 the argument indices go beyond the number of arguments passed.  Apparently the example used to have "Sweden" as an argument, but was removed.  The code listing in the book is correct, but the file in the repo is incorrect.

**Comment by markjprice** [comment]
Thanks, I've fixed this now.
