### ISSUE TITLE
Page 261 typo

### ISSUE THREAD

**Issue by vladmeici** [markjprice/cs12dotnet8#28]
Hi Mark,

There is an extra space in the code snippet on page 261 in the list of parameters for OptionalParameters method:
string command  = "Run!"

Best,
Vlad

**Comment by markjprice** [comment]
Thanks. I have added an errata item for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-261---passing-optional-parameters
