### ISSUE TITLE
Polyglot cannot work without .Net7

### ISSUE THREAD

**Issue by devcloud-ops** [markjprice/cs12dotnet8#3]
Regarding this:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/ch01-polyglot-notebooks.md

I faced issues installing polyglot because .Net 7 was not installed in my machine. It's worth mentioning in above markdown page, else others too will waste time figuring it out. Dots to the rescue, saved me some time.

**Comment by markjprice** [comment]
Thanks! I have added a warning to that page and added this as an errata item: https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-10---installing-other-extensions
