### ISSUE TITLE
Book Links Chapter03 - Coding problems in interviews - FizzBuzz for programming interviews

### ISSUE THREAD

**Issue by Emopusta** [markjprice/cs12dotnet8#30]
In book-links.md Chapter03 - Coding problems in interviews section `FizzBuzz for programming interviews` link not working. https://github.com/markjprice/cs12dotnet8/blob/main/docs/book-links.md#coding-problems-in-interviews

**Comment by markjprice** [comment]
Thanks for spotting this. I have updated the link to two new links about FizzBuzz in interviews.
