### ISSUE TITLE
Some Information Left From the Previous Topic

### ISSUE THREAD

**Issue by cmkaya** [markjprice/cs12dotnet8#31]
Chapter: 8
Title: Generating GUIDs
Page: 421

There seems to be some confusion in step one. It says to add statements to access a shared `Random` instance and use its methods to generate random numbers.  I'm not sure how this relates to generating a GUID, especially considering the code provided.

**Comment by markjprice** [comment]
Thanks, Cem. I have added an errata item for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-421---generating-guids
