### ISSUE TITLE
Compatibility issues when trying to work through EF functionality.

### ISSUE THREAD

**Issue by BoredNumb** [markjprice/cs12dotnet8#33]
First of all, I have little to complain about with the book.  I'm learning quite a bit in trying to update my C# version.

I am running into issues when I try to work through Chapters 10 and 13.  I'm using:

VS2022
SQL Server 2019 (located on my local machine)

I'll use the Chapter 10 instructions to show what is happening.

I follow along with the online instructions for SQL Server.  I've installed the Northwind database and I'm building the solution.  I created the initial solution (WorkingWithEFCore) and the instructions want me to add the using for System.Console and the references to Microsoft.Data.SqlClient and Microsft.EntityFrameworkCore.SqlServer.  I building the project fails with a warning that the Microsoft.Data.SqlClient version 5.1.1 is a vulnerable package and that System.Security.Cryptography.Cng version 5.0.0 not being compatible with net8.0.  There is a similar conflict with System.Windows.Extensions version 6.0.0.

I'm guessing that the Microsoft.Data.SqlClient library or the Microsoft.EntityFrameworkCore.SqlServer relies on the offending libraries but I'm not sure how to resolve the problem.  I could work through the exercises with the vulnerable libraries if the project built but that wouldn't help much in the end as the reason I'm updating my knowledge is that I need to update a couple of projects for work and having the vulnerable library would not be permitted.

Any ideas on how I can move forward with this?  Thanks!

**Comment by markjprice** [comment]
Visual Studio 2022 advises you to upgrade to 5.2.0, as shown in the screenshot. Just do that.
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/b259eba7-0614-46fa-83a1-ace5b54616fd)

**Comment by markjprice** [comment]
I have updated the appropriate page in the GitHub repo: https://github.com/markjprice/cs12dotnet8/blob/main/docs/sql-server/README.md#defining-the-northwind-database-context-class

**Comment by BoredNumb** [comment]
The dependencies are resolved but now the scaffolding command returns the following error:

Your startup project 'Northwind.EntityModels.SqlServer' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

I added 
    <PackageReference Version="8.0.4" Include="Microsoft.EntityFrameworkCore.Design" />
to the project file as well and this corrected my issue.

**Comment by markjprice** [comment]
Yes, the instructions to add `Microsoft.EntityFrameworkCore.Design` are in the book and apply to both SQLite and SQL Server. In the next edition, I will add a note in the book to explicitly say this, although hopefully it is implied that SQL Server users must complete everything in the book except when explicitly about SQLite.
