### ISSUE TITLE
Broken YouTube link

### ISSUE THREAD

**Issue by zaynchoudry** [markjprice/cs12dotnet8#34]
In Chapter 02 there is a reference to this link of a video demonstrating Arabic programming, the video no longer exists: https://youtu.be/dkO8cdwf6v8

**Comment by markjprice** [comment]
Thanks. I have added an errata item for this:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-65---comparing-programming-languages-to-human-languages
