### ISSUE TITLE
'RenderModeAuto' could not be found

### ISSUE THREAD

**Issue by LesF** [markjprice/cs12dotnet8#35]
I have opened the PracticalApps solution then updated all the nuget packages to the latest stable.  Then I compiled the solution, and get several errors in two of the projects.  In Northwind.Blazor.Wasm page Fibonacci.razor I get:

Error CS0246 The type or namespace name 'RenderModeAuto' could not be found (are you missing a using directive or an assembly reference?) Northwind.Blazor.Wasm D:\Projects\cs12dotnet8\code\PracticalApps\Northwind.Blazor.Wasm\Pages\Fibonacci.razor	1	Active

Error CS0246 The type or namespace name 'RenderModeAutoAttribute' could not be found (are you missing a using directive or an assembly reference?) Northwind.Blazor.Wasm D:\Projects\cs12dotnet8\code\PracticalApps\Northwind.Blazor.Wasm\Pages\Fibonacci.razor	1	Active

Haven't worked thru the chapter yet, there might be something I need to tweak, just wondered if this solution is expected to build ok as it is.

**Comment by markjprice** [comment]
Sorry, that's my mistake. I've fixed it in the GitHub repository code now. The following statement:
```cs
@attribute [RenderModeAuto]
```
Should have been:
```cs
@rendermode RenderMode.InteractiveAuto
```

**Comment by LesF** [comment]
All good now. Thanks
