### ISSUE TITLE
CS 12 .Net 8 page 148

### ISSUE THREAD

**Issue by servbot007** [markjprice/cs12dotnet8#37]
In the section "How negative numbers are represented in binary", the last three WriteLine statements are missing the extra int.MaxValue, i, and int.MinValue respectively in their argument lists.

Easy fix but noticed this wasn't on the errata page.

**Comment by markjprice** [comment]
I don't know what you mean. What do you think the code should be?

**Comment by markjprice** [comment]
The code statement:
```cs
WriteLine("{0,12} {1,34}", "Decimal", "Binary");
```
Outputs the headers for the table:
```
        Decimal      Binary
```
The statement:
```cs
WriteLine("{0,12} {0,34:B32}", int.MaxValue);
```
Outputs the first row for the maximum value only:
```
2147483647 01111111111111111111111111111111
```
The loop:
```cs
for (int i = 8; i >= -8; i--)
{
WriteLine("{0,12} {0,34:B32}", i);
}
```
Outputs the values between 8 and -8:
```
8 00000000000000000000000000001000
7 00000000000000000000000000000111
6 00000000000000000000000000000110
5 00000000000000000000000000000101
4 00000000000000000000000000000100
3 00000000000000000000000000000011
2 00000000000000000000000000000010
1 00000000000000000000000000000001
0 00000000000000000000000000000000
-1 11111111111111111111111111111111
-2 11111111111111111111111111111110
-3 11111111111111111111111111111101
-4 11111111111111111111111111111100
-5 11111111111111111111111111111011
-6 11111111111111111111111111111010
-7 11111111111111111111111111111001
-8 11111111111111111111111111111000
```
And the final statement:
```cs
WriteLine("{0,12} {0,34:B32}", int.MinValue);
```
outputs the minimum value:
```
-2147483648 10000000000000000000000000000000
```

**Comment by markjprice** [comment]
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/cf3ab88f-707d-4c58-9e32-5ee0080ae58c)

**Comment by markjprice** [comment]
I've created an improvement item for this:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-99---custom-number-formatting

**Comment by servbot007** [comment]
I do stand corrected. I subconsciously typed this code as {0} and {1}. I went back into the book and see {0} referenced in both places.

Thank you for getting back to me and helping me see this.

Cheers!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
