### ISSUE TITLE
Chapter 12 Page 645

### ISSUE THREAD

**Issue by pmarangoni** [markjprice/cs12dotnet8#40]
> 11. In **EmployeeTerritory.cs**, make the TerritoryId property required.

There is **EmployeeTerritory.cs** class file in the project (I'm using SQL Server not SQLite).  That lookup table is dealt with in the **NorthwindContext.c**s file in the function **OnModelCreating**.

**Comment by markjprice** [comment]
![image](https://github.com/markjprice/cs12dotnet8/assets/14040265/d064d892-29c6-4288-a671-8d6f3ad33dd9)

The book instructions are for SQLite not SQL Server so step 11 does not apply to you.

**Comment by markjprice** [comment]
I've added an improvement item for this:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-634---creating-the-northwind-database
