### ISSUE TITLE
Error on page 265

### ISSUE THREAD

**Issue by ssvyst** [markjprice/cs12dotnet8#42]
Greetings,

I noticed a small error on page 265 of the book. In the sentence "In Program.cs, add statements to declare some more variables, including an out parameter named f declared inline, as shown in the following code:" it should be "h" instead of "f" as you can see in the following code illustration: 
![Capture](https://github.com/markjprice/cs12dotnet8/assets/168045695/9ed17514-6a22-4481-9a1f-070590ff33c4)

Regards,
Stanislav

**Comment by markjprice** [comment]
Thanks! I have added this as an errata item here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-265---controlling-how-parameters-are-passed
