### ISSUE TITLE
Page 110 question/remark

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#43]
![image](https://github.com/markjprice/cs12dotnet8/assets/15747788/e362c1e2-1129-4281-b255-ba2efae88be8)

**Comment by markjprice** [comment]
You are correct! Thanks! I have added this as an errata here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-110---handling-platforms-that-do-not-support-an-api
