### ISSUE TITLE
Page 236 - DateTime.UnixEpoch

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#46]
Maybe DateTime.UnixEpoch is not the best example for a Read-only field, because working through the chapter the reader would have just changed the TargetFramework to netstandard2.0, and UnixEpoch is not available until 2.1.

**Comment by markjprice** [comment]
Thanks! I have added an improvement item for this here: https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-236---understanding-members

**Comment by rmantel23** [comment]
Thanks again Mark!

Maybe another idea. When reading this section, one could wonder why .NET wouldn't use a constant instead of a read-only field for something like UnixEpoch, since it is obviously a fixed. I assume the answer is that only the C# built-in types may be declared as const. It might be helpful to add this where you explain the constant.

**Comment by markjprice** [comment]
I've updated the improvement item.
