### ISSUE TITLE
Page 281 - extra comma

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#47]
![image](https://github.com/markjprice/cs12dotnet8/assets/15747788/b205d5f5-24a4-42ce-86a5-359318417905)

**Comment by markjprice** [comment]
There are multiple places were I use a trailing comma in the book. I have previously added an improvement item about this here: https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-144---list-pattern-matching-with-arrays
I will update the item to list all the pages that I use a trailing comma.
