### ISSUE TITLE
Page 295 - fields in properties region

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#48]
![image](https://github.com/markjprice/cs12dotnet8/assets/15747788/5d399630-83b1-4c84-a4e9-b0b7f649e649)

**Comment by markjprice** [comment]
Thanks for spotting this typo. I've added an errata for it here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-295---setting-up-a-class-library-and-console-application
