### ISSUE TITLE
Minor issue in name of a preference

### ISSUE THREAD

**Issue by TheFumblebee** [markjprice/cs12dotnet8#5]
Hi Mark,

Hope this isn't too pedantic and apologies if it is.

Minorly incorrect string - that you might be interested in correcting going forward - in Chapter 1, page 43 on my Kindle, where you are discussing inline/inlay hints.  The option you refer to as "Display inline parameter hint names" is "Display inline parameter name hints".

Easy error to roll with, no skin off my back, just figured you might want it flagged for ya.

Best,
Fumblebee

**Comment by markjprice** [comment]
Thanks! I have added an errata item here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-43---configuring-inline-aka-inlay-hints
