### ISSUE TITLE
Page 296 - Spouses

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#50]
Similar to Children on page 295.

You write:

1. In Person.cs, add properties with private backing storage fields to indicate if that person is 
married and to whom, as shown in the following code:

But Spouses is a public field.

![image](https://github.com/markjprice/cs12dotnet8/assets/15747788/4908c776-e905-452d-b825-6e0cde437d9f)

**Comment by markjprice** [comment]
Fixed:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-296---implementing-functionality-using-methods
