### ISSUE TITLE
Page 305 - 'named'

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#51]
It might just be me, but I don't understand the word 'named' in this sentence:

Although the code works, there is potential for mistakes because literally any type can be used for the 
key or value. If another developer used your variable **named** and expected all the items to be a certain 
type, they might cast them to that type and get exceptions because some values might be a different 
type. A lookup object with lots of items would also give poor performance.

**Comment by markjprice** [comment]
Thanks. I've added an errata for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-305---working-with-non-generic-types
