### ISSUE TITLE
Pages 375 and 400 - navigation in source

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#55]
Since the option is called 'Enable navigation to Source' it would probably be better to instruct the reader to search for that (to instead of in), so it highlights the option.

**Comment by markjprice** [comment]
Thanks. I've added errata items for these:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-375---revealing-the-location-of-a-type
