### ISSUE TITLE
Page 413 - questions 5, 9 & 10 in exercise 7.1

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#56]
Maybe in earlier versions the information about porting was included in the main text, but now the reader won't be able to answer these questions without first reading the online-only section about porting which is in a later exercise (7.3).

**Comment by markjprice** [comment]
Thanks. I've added an improvement item for this:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-413---exercise-71--test-your-knowledge
