### ISSUE TITLE
Page 241 Fig 5.1 Detail

### ISSUE THREAD

**Issue by Emopusta** [markjprice/cs12dotnet8#57]
Above Fig 5.1 on page 241 you mentioned "You will see the ....... but note that the class is in a .Net Standard 2.0 class library assembly and has a method named ToString, as shown in Figure 5.1:" We can see the Assembly is netstandard 2.0 but there is no ToString method in the image. I don't know is it necessary but for someone who doesn't follow with computer, it seems the image is not fully detailed due to its explanation above.

**Comment by markjprice** [comment]
Thanks. I have added an errata item for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-241---inheriting-from-systemobject
