### ISSUE TITLE
page 430, 1st paragraph - regexp optimizations

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#61]
You write 'But until now, they haven't received much optimization attention', but then describe optimizations that have happened. Is this maybe a leftover from an earlier version?

Maybe change to 'until recently' or 'until .NET 5 and 7'.

**Comment by markjprice** [comment]
Thanks! I have added an errata item for this here: https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-430---regular-expression-performance-improvements
