### ISSUE TITLE
Sample code chapter Implementing Interfaces and Inheriting Classes | Inheriting from classes section

### ISSUE THREAD

**Issue by hsuyanto** [markjprice/cs12dotnet8#63]
on steps no. 3 sample code:
Employee john = new()
{
  Name = "John Jones",
  Born = new(year: 1990, month: 7, day: 28,
    hour: 0, minute: 0, second: 0, offset: TimeSpan.Zero)**)** //extra closing parenthesis need to be removed
};
john.WriteToConsole();

should be:
Employee john = new()
{
  Name = "John Jones",
  Born = new(year: 1990, month: 7, day: 28,
    hour: 0, minute: 0, second: 0, offset: TimeSpan.Zero)
};
john.WriteToConsole();

**Comment by markjprice** [comment]
This is already in the errata:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-344---inheriting-from-classes
