### ISSUE TITLE
Capter 2 AsyncConsole non top level version

### ISSUE THREAD

**Issue by b7f7** [markjprice/cs12dotnet8#64]
async Main does not support int or void return but needs `static async Task Main` would be good if that is explained, but explaing async here looks out of place

**Comment by markjprice** [comment]
Doesn't the note on page 112 do what you're asking for?
![image](https://github.com/user-attachments/assets/62adc4b6-5d82-4e95-993b-b689e89d72b3)

I agree this section is a little out-of-place. I will consider removing it in the next edition.

**Comment by b7f7** [comment]
yes, for some reason i ignored it because i was not using Net 5 and i thought it was reffereing to Main not supporting async
