### ISSUE TITLE
Page 564 - SQL Server while using SQLite in this chapter as example

### ISSUE THREAD

**Issue by rmantel23** [markjprice/cs12dotnet8#68]
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
 optionsBuilder.**UseSqlServer**(connectionString)
 .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
}

Since in this whole chapter you are using SQLite for the examples, why use 'UseSqlServer' here instead of 'UseSqllite'?

**Comment by markjprice** [comment]
I've added an improvement item for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-564---controlling-the-tracking-of-entities
