### ISSUE TITLE
Page 96, example 2.: Currency issue

### ISSUE THREAD

**Issue by centpede** [markjprice/cs12dotnet8#7]
Dear Mark,

page 96, example 2.:

Output is without curreny, but question mark:
_**12 apples cost 4,20 ?**_

Solution: Put the following lines on top for right encoding:
```
using System.Text;
Console.OutputEncoding = Encoding.Default;
```

Output now is with currency:
_**12 apples cost 4,20€**_

Thanks,
Robin

**Comment by markjprice** [comment]
Thanks, Robin. I have added this as an improvement item:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-96---formatting-using-numbered-positional-arguments--formatting-using-interpolated-strings
