### ISSUE TITLE
Page 62 - Collapse and expand blocks

### ISSUE THREAD

**Issue by donaldmaisey** [markjprice/cs12dotnet8#70]
Just noticed this:

The latest version of VS 2022 (v17.11) now uses the down or right arrow the same a VS Code (rather than [-] or [+]).

Regards

**Comment by markjprice** [comment]
Yes, I recently noticed that too. I've updated the screenshot for the ninth edition:
<img width="797" alt="B22322_02_02" src="https://github.com/user-attachments/assets/62951486-8e6f-4a7a-a008-3d2d66449e77">
