### ISSUE TITLE
Chapter 12 to 16 - there is no chapter 16 in the book

### ISSUE THREAD

**Issue by s3ba-b** [markjprice/cs12dotnet8#74]
In the book at page 5, in the section "Choosing the appropriate tool and application type for learning" there is a sentence that states: "in Chapter 12 to 16, you will build websites, services, and web browser apps".

I don't see a Chapter 16 in the table of contents, so I guess there should be a sentence corrected to "in Chapter 12 to 15".

Really small issue, but I let you know.

**Comment by markjprice** [comment]
Thanks. I've added an errata item for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-5---choosing-the-appropriate-tool-and-application-type-for-learning
