### ISSUE TITLE
[Suggestion of improvement] Listing and removing versions of .NET - first paragraph

### ISSUE THREAD

**Issue by s3ba-b** [markjprice/cs12dotnet8#75]
I had trouble understanding (or more like a making sure that I understand correctly) this fragment:

".NET runtime updates are compatible with a major version such as 8.x, and updated releases of the
.NET SDK maintain the ability to build applications that target previous versions of the runtime, which
enables the safe removal of older versions."

and I had to ask ChatGPT about this:

"(...) This explanation is about how updates in the .NET ecosystem work, particularly focusing on the compatibility of the .NET runtime and SDK (Software Development Kit) versions.

Here's a breakdown of what this means:

1. **.NET Runtime Compatibility with Major Versions**:
   - In .NET, a major version is represented by a number (e.g., 8.x, where "8" is the major version, and "x" represents minor or patch updates).
   - When the runtime is updated, these updates are compatible with the current major version. So, all updates in the 8.x range are compatible with each other.
   - This compatibility means that if you have an application running on .NET 8.0, it should work smoothly if you update to .NET 8.1 or 8.2, etc., without any issues in functionality or breaking changes.

2. **.NET SDK Compatibility with Previous Runtime Versions**:
   - The .NET SDK is what developers use to build and compile .NET applications. It includes tools and libraries for development.
   - When you update the .NET SDK to a newer version, it can still build applications that target older runtime versions. For example, if you update to the .NET SDK for .NET 8, you can still compile applications that are set to run on .NET 7 or even .NET 6.
   - This backward compatibility in the SDK makes it easier for developers to use the latest tools and features in development while ensuring that their applications can still target older runtime environments.

3. **Safe Removal of Older Versions**:
   - Because of the compatibility in the SDK and the runtime, it's generally safe to remove older versions of the runtime from your system once you have upgraded.
   - This is helpful for managing dependencies and freeing up system resources, as you don’t need to keep every old version of the runtime on your machine.

In essence, this approach allows for smooth updates and simplified version management, enabling developers to use the latest SDK features while supporting applications across multiple runtime versions."

My suggestion:

Explain each part of the sentence separately and give examples. You don't have to be extensive like the ChatGPT's response, but be a bit less enigmatic :)

**Comment by markjprice** [comment]
Thanks. I've added this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/improvements.md#page-15---listing-and-removing-versions-of-net
