### ISSUE TITLE
Update Rider documentation for "Do not use top-level statements

### ISSUE THREAD

**Issue by mihailocv** [markjprice/cs12dotnet8#78]
### Description 
The documentation for Rider in the file `cs12dotnet8/docs/code-editors/rider.md` is outdated. Chapter 1 - Adding a second project using JetBrains Rider states that Rider does not have the option to disable top-level statements when creating a file. However, starting with **Rider 2024.3**, this option is now available.

### Steps to reproduce 
1. Open Rider 2024.3.  
2. Click on **New Solution**.  
3. In the new solution window:  
   - On the left side, under **Project Type**, select **Console**.  
   - On the right side, below **Type**, you will see the newly added option for "Do not use top-level statements."  

### Suggested Fix
Update the documentation to reflect that the "Do not use top-level statements" option is available in Rider 2024.3 across all operating systems.

### Additional Information
I use Ubuntu 24.04.1 LTS, but this change should apply to all supported platforms (Windows, macOS, and Linux).  
I am attaching a screenshot demonstrating this feature in Rider 2024.3.

![Screenshot from 2024-12-14 16-36-23](https://github.com/user-attachments/assets/ace2c9d0-b08d-4a4a-94b3-e2df28e42602)

**Comment by markjprice** [comment]
Thanks! I have updated the Rider page for both the 8th and 9th editions:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/code-editors/rider.md
