### ISSUE TITLE
Improvement for Exercise 8.3 page 462

### ISSUE THREAD

**Issue by vladmeici** [markjprice/cs12dotnet8#79]
If you run all the tests at once(not one by one), two will be success and two fill fails with the error: The process cannot access the file '...\cs12dotnet8Playground\Chapter08\Ch08Ex03NumbersAsWordsTests\bin\Debug\net8.0\log.txt' because it is being used by another process.

When you create the text writer in NumbersToWords.cs, you can add a "using" for the text writer object in order to ensure that it is disposed after it is used:        
`// write to a text file in the project folder`
`using var textWriter = new TextWriterTraceListener(File.AppendText("log.txt"));`
`Trace.Listeners.Add(textWriter);`

**Comment by markjprice** [comment]
Good idea. Done in both 8th and 9th edition solutions.
