### ISSUE TITLE
Sync between code on page 469 and console output

### ISSUE THREAD

**Issue by vladmeici** [markjprice/cs12dotnet8#80]
In the console output for the code on page 469, the text "Deleting it..." appears a a new row, but there is nothing in the code that indicates this. You can either:
1. Use `WriteLine("\nDeleting it...");`
2. Or use `ReadLine();` instead of `ReadKey(intercept: true);`

Otherwise, the text "Deleting it..." will appear just after "...press any key."

Update: Same situation found on page 471.

**Comment by markjprice** [comment]
Thanks. I've added an errata item for this here:
https://github.com/markjprice/cs12dotnet8/blob/main/docs/errata/errata.md#page-468---managing-directories-managing-files
