### ISSUE TITLE
Grammatical improvement on page 474 about FileShare

### ISSUE THREAD

**Issue by vladmeici** [markjprice/cs12dotnet8#81]
When I read the sentence _"FileShare: This controls locks on the file to allow other processes the specified level of access, like Read."_ I felt like there is something missing that should link _"processes"_ with _"specified level of access"_.

I think this sounds better: _"... to allow other processes **to have** the specified level of access, ..."_.

**Comment by markjprice** [comment]
Thanks. I have added an improvement item for this here:
https://github.com/markjprice/cs13net9/blob/main/docs/errata/improvements.md#page-488---controlling-how-you-work-with-files
