### ISSUE TITLE
Cannot find tables

### ISSUE THREAD

**Issue by DrAvriLev** [markjprice/cs12dotnet8#9]
Hello Mark,
 Relating to Chapter 10:
I got this message after issuing the dotnet  ef scaffold command copied from your Github:

F:\EF core Learning\Chapter10\WorkingWithEFCore>dotnet ef dbcontext scaffold "Data Source=Northwind.db" Microsoft.EntityFrameworkCore.Sqlite --table Categories --table Products --output-dir AutoGenModels --namespace WorkingWithEFCore.AutoGen --data-annotations --context NorthwindDb

This is what I got:

To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
Unable to find a table in the database matching the selected table 'Categories'.
Unable to find a table in the database matching the selected table 'Products'.

Tried it from within VS2022 and from CMD - same results... :(

Helkp please,
Avri

**Comment by markjprice** [comment]
You must make sure that the `Northwind.db` database file is in the directory that you run the `dotnet ef` command e.g. in your case `F:\EF core Learning\Chapter10\WorkingWithEFCore`. If it is not, then an empty database file will be created by the SQLite provider.

**Comment by markjprice** [comment]
Make sure you have completed the steps correctly in the section titled **Creating the Northwind sample database for SQLite** on page 519 to create the `Northwind.db` database file is in the `WorkingWithEFCore` project folder.

**Comment by DrAvriLev** [comment]
I send you a screen shot 

You can see that the database is in the same folder as the command

**Comment by markjprice** [comment]
There might be a database file with that name in that folder but your error message is telling you that it does not contain the tables.

**Comment by markjprice** [comment]
Your screenshot is not shown.

**Comment by DrAvriLev** [comment]
You’re right!

There was an empty database in that folder.

Thank you very much.

 

Happy new 2024

Avri
